name = "topupforme-frontend"
main = ".open-next/worker.js"
compatibility_date = "2024-10-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pnpm run build"

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_API_BASE_URL = "https://api.topupforme.com"
